import { useMemo } from 'react';
import { Download } from 'lucide-react';
import type { UsageData } from '../types';
import dayjs from 'dayjs';
import { formatTokens, formatUSD } from '../utils/format';
import { summarizeUsage } from '../utils/usage';

export default function ExportMarkdown({ data }: { data: UsageData }) {
  const markdown = useMemo(() => {
    const summary = summarizeUsage(data);
    const totals = summary.totals;
    const daily = data.daily ?? [];
    const sessions = data.sessions ?? [];

    const lifetimeTokens = totals?.totalTokens ?? 0;
    const lifetimeCost = totals?.costUSD ?? 0;

    const mostActiveDay = [...daily].sort((a, b) => b.totalTokens - a.totalTokens)[0];
    const avgDaily = daily.length > 0 ? Math.round(lifetimeTokens / daily.length) : 0;

    const mostUsedModel = summary.modelTotals[0]?.name ?? '-';

    const lines: string[] = [
      '# Local AI Usage Report',
      '',
      `> Generated at ${dayjs().format('YYYY-MM-DD HH:mm:ss')}`,
      '> Data source: local ccusage-supported session logs',
      '',
      '## Overview',
      '',
      `- **Lifetime Tokens**: ${formatTokens(lifetimeTokens)}`,
      `- **Estimated Cost**: ${formatUSD(lifetimeCost)}`,
      `- **Most Active Day**: ${mostActiveDay?.date ?? '-'} (${formatTokens(mostActiveDay?.totalTokens ?? 0)})`,
      `- **Average Daily Usage**: ${formatTokens(avgDaily)}`,
      `- **Most Used Model**: ${mostUsedModel}`,
      '',
      '## Source Breakdown',
      '',
      '| Source | Sessions | Tokens | Cost |',
      '|--------|----------|--------|------|',
    ];

    summary.sourceTotals.forEach((source) => {
      lines.push(
        `| ${source.label} | ${source.sessions} | ${formatTokens(source.totalTokens)} | ${formatUSD(source.costUSD)} |`
      );
    });

    lines.push(
      '',
      '## Model Breakdown',
      '',
      '| Model | Sessions | Tokens | Cost |',
      '|-------|----------|--------|------|'
    );

    summary.modelTotals.slice(0, 20).forEach((model) => {
      lines.push(
        `| ${model.name} | ${model.sessions} | ${formatTokens(model.totalTokens)} | ${formatUSD(model.costUSD)} |`
      );
    });

    lines.push(
      '',
      '## Daily Breakdown',
      '',
      '| Date | Input | Cached | Output | Reasoning | Total | Cost |',
      '|------|-------|--------|--------|-----------|-------|------|',
    );

    [...daily]
      .sort((a, b) => a.date.localeCompare(b.date))
      .forEach((d) => {
        lines.push(
          `| ${d.date} | ${formatTokens(d.inputTokens)} | ${formatTokens(d.cachedInputTokens)} | ${formatTokens(d.outputTokens)} | ${formatTokens(d.reasoningOutputTokens)} | ${formatTokens(d.totalTokens)} | ${formatUSD(d.costUSD)} |`
        );
      });

    lines.push('', '## Monthly Summary', '', '| Month | Input | Cached | Output | Reasoning | Total | Cost |', '|-------|-------|--------|--------|-----------|-------|------|');

    (data.monthly ?? [])
      .sort((a, b) => a.month.localeCompare(b.month))
      .forEach((m) => {
        lines.push(
          `| ${m.month} | ${formatTokens(m.inputTokens)} | ${formatTokens(m.cachedInputTokens)} | ${formatTokens(m.outputTokens)} | ${formatTokens(m.reasoningOutputTokens)} | ${formatTokens(m.totalTokens)} | ${formatUSD(m.costUSD)} |`
        );
      });

    lines.push('', '## Sessions', '', '| Date | Source | Session | Total Tokens | Models | Cost |', '|------|--------|---------|--------------|--------|------|');

    [...sessions]
      .sort((a, b) => b.lastActivity.localeCompare(a.lastActivity))
      .slice(0, 50)
      .forEach((s) => {
        const models = Object.keys(s.models).join(', ');
        lines.push(
          `| ${dayjs(s.lastActivity).format('YYYY-MM-DD HH:mm')} | ${s.source ?? s.agent ?? 'unknown'} | ${s.sessionFile} | ${formatTokens(s.totalTokens)} | ${models} | ${formatUSD(s.costUSD)} |`
        );
      });

    lines.push('', '---', '', '*This report was generated by [Local AI Usage Dashboard](https://github.com/7oru/local-ai-usage-dashboard)*');

    return lines.join('\n');
  }, [data]);

  const handleDownload = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `local-ai-usage-report-${dayjs().format('YYYY-MM-DD')}.md`;
    try {
      a.click();
    } finally {
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm mb-8">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-slate-800 font-semibold">Markdown Export</h3>
        <button
          onClick={handleDownload}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 transition-colors"
        >
          <Download size={16} />
          Download Markdown Report
        </button>
      </div>
      <p className="text-slate-500 text-sm mb-3">
        Generate a clean Markdown report for documenting your AI-assisted development workflow.
      </p>
      <div className="bg-slate-50 rounded-lg border border-slate-200 p-4 overflow-auto max-h-64">
        <pre className="text-xs text-slate-700 font-mono whitespace-pre">{markdown}</pre>
      </div>
    </div>
  );
}
